version: '3'

services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    web:
        build: .
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
    server:
        build: ./frontend
        environment:
            NODE_ENV: production
        ports:
            - 5173:5173            
