# Generated by Django 4.2.6 on 2024-01-21 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0002_course_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
