# Generated by Django 5.0.1 on 2024-01-22 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0003_alter_course_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprogress",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_progress",
                to="learn.course",
            ),
        ),
    ]
