# Generated by Django 5.0.1 on 2024-01-22 12:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0004_alter_userprogress_course"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workouts",
            old_name="set",
            new_name="sets",
        ),
    ]
