# Generated by Django 5.0.1 on 2024-02-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0007_workouts_demo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workouts",
            name="demo",
            field=models.URLField(),
        ),
    ]
