# Generated by Django 5.0.1 on 2024-02-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0008_alter_workouts_demo"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[("P", "Pending"), ("A", "Approved"), ("R", "Rejected")],
                default="P",
                max_length=1,
            ),
        ),
    ]
