# Generated by Django 5.0.1 on 2024-02-07 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0009_course_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursecomments",
            name="parent_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="learn.coursecomments",
            ),
        ),
    ]
