# Generated by Django 5.0.1 on 2024-02-13 16:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0010_alter_coursecomments_parent_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprogress",
            old_name="progress",
            new_name="user",
        ),
    ]
