# Generated by Django 5.0.1 on 2024-02-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0011_rename_progress_userprogress_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workouts",
            name="excertion",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workouts",
            name="intensity",
            field=models.CharField(
                blank=True,
                choices=[("L", "Low"), ("M", "Medium"), ("H", "High")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workouts",
            name="reps",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workouts",
            name="rest_time",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workouts",
            name="sets",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
