# Generated by Django 5.0.1 on 2024-02-21 11:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0012_alter_workouts_excertion_alter_workouts_intensity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="blog_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blog",
            name="blog_updated",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
