# Generated by Django 5.0.1 on 2024-02-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0013_blog_blog_created_blog_blog_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcomments",
            name="comment",
            field=models.TextField(),
        ),
    ]
