# Generated by Django 5.0.1 on 2024-03-15 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0016_courserating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="correctexerciseform",
            name="description",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="workouts",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_workouts",
                to="learn.course",
            ),
        ),
        migrations.AlterField(
            model_name="workouts",
            name="exercise",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="wrongexerciseform",
            name="description",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="learn.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lecture", models.URLField()),
                ("overview", models.TextField()),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="learn.section",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="workouts",
            name="section",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workouts",
                to="learn.sectionitem",
            ),
            preserve_default=False,
        ),
    ]
