# Generated by Django 5.0.1 on 2024-03-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0017_alter_blog_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectionitem",
            name="lecture",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sectionitem",
            name="overview",
            field=models.TextField(blank=True, null=True),
        ),
    ]
