# Generated by Django 5.0.1 on 2024-03-16 14:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0018_alter_sectionitem_lecture_alter_sectionitem_overview"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workouts",
            old_name="section",
            new_name="section_item",
        ),
    ]
