# Generated by Django 5.0.1 on 2024-03-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0020_remove_workouts_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="week",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
