# Generated by Django 5.0.1 on 2024-03-19 17:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0023_remove_section_week"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionitem",
            name="title",
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
