# Generated by Django 5.0.1 on 2024-03-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0025_rename_overview_sectionitem_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workouts",
            name="exercise",
            field=models.CharField(max_length=200),
        ),
    ]
