# Generated by Django 5.0.1 on 2024-03-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0026_alter_workouts_exercise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_created",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_updated",
            field=models.DateField(auto_now_add=True),
        ),
    ]
