# Generated by Django 5.0.1 on 2024-03-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0027_alter_course_course_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_updated",
            field=models.DateField(auto_now=True),
        ),
    ]
