# Generated by Django 5.0.1 on 2024-03-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0028_alter_course_course_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
