# Generated by Django 5.0.1 on 2024-03-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0029_course_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_created",
            field=models.DateField(),
        ),
    ]
