# Generated by Django 5.0.1 on 2024-03-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0030_alter_course_course_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_created",
            field=models.DateField(blank=True, null=True),
        ),
    ]
