# Generated by Django 5.0.1 on 2024-03-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0034_rename_title_section_heading_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="correctexerciseform",
            name="description",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="workouts",
            name="exercise",
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name="wrongexerciseform",
            name="description",
            field=models.CharField(max_length=200),
        ),
    ]
