# Generated by Django 5.0.1 on 2024-03-31 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0035_alter_correctexerciseform_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coursecontent",
            old_name="lecture",
            new_name="preview",
        ),
    ]
