# Generated by Django 5.0.1 on 2024-04-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0036_rename_lecture_coursecontent_preview"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursecontent",
            name="weeks",
        ),
        migrations.AddField(
            model_name="course",
            name="weeks",
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
    ]
