# Generated by Django 5.0.1 on 2024-04-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0037_remove_coursecontent_weeks_course_weeks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=6, null=True
            ),
        ),
    ]
