# Generated by Django 5.0.1 on 2024-04-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0038_alter_course_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
