# Generated by Django 5.0.1 on 2024-04-16 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0039_alter_course_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="learn.coursecontent",
            ),
        ),
    ]
