# Generated by Django 5.0.1 on 2024-04-16 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0040_alter_section_course"),
    ]

    operations = [
        migrations.RenameField(
            model_name="section",
            old_name="course",
            new_name="course_content",
        ),
    ]
