# Generated by Django 5.0.1 on 2024-05-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0041_rename_course_section_course_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="correctexerciseform",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workouts",
            name="exercise",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wrongexerciseform",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
