# Generated by Django 5.0.1 on 2024-05-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0043_alter_correctexerciseform_demo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sectionitem",
            name="description_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
