# Generated by Django 5.0.1 on 2024-05-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0045_course_is_draft"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
