# Generated by Django 5.0.1 on 2024-05-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0046_alter_course_course_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_created",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
