# Generated by Django 5.0.1 on 2024-05-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0048_alter_course_course_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
