# Generated by Django 5.0.1 on 2024-05-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0049_alter_course_course_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
