# Generated by Django 5.0.1 on 2024-05-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0050_alter_course_course_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
