# Generated by Django 5.0.1 on 2024-06-02 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0051_course_read"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprogress",
            old_name="weeks_completed",
            new_name="sections_completed",
        ),
        migrations.AddField(
            model_name="section",
            name="is_clicked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="enrollment",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress",
                to="learn.enrollment",
            ),
        ),
    ]
