# Generated by Django 5.0.1 on 2024-06-02 17:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "learn",
            "0052_rename_weeks_completed_userprogress_sections_completed_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprogress",
            name="enrollment",
        ),
    ]
