# Generated by Django 5.0.1 on 2024-06-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0054_remove_section_is_clicked_usersection"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="status",
            field=models.CharField(
                choices=[("P", "Pending"), ("A", "Approved"), ("R", "Rejected")],
                default="P",
                max_length=1,
            ),
        ),
    ]
