# Generated by Django 5.0.1 on 2024-06-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0057_delete_image_remove_blog_status_alter_blog_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="summary",
            field=models.CharField(default="nothing", max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blog",
            name="blog_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
