# Generated by Django 5.0.1 on 2024-06-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("learn", "0058_blog_summary_alter_blog_blog_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcomments",
            name="comment_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
