name: Django CI

on: push

jobs:
  build:
    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: jericho1050
          POSTGRES_PASSWORD: ${{ secrets.PASSWORD }}
          POSTGRES_DB: mydatabase
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Django unit tests
      env:
        PASSWORD : ${{ secrets.PASSWORD }}
      run: |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py test