name: Django CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Run Django unit tests
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python manage.py makemigrations
        python manage.py migrate
        python manage.py test

