name: Django CI

on: push

jobs:
  build:
    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: jericho1050
          POSTGRES_PASSWORD: ${{ secrets.PASSWORD }}
          POSTGRES_DB: mydatabase
        ports:
          - 5432:5432

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up PostgreSQL
      uses: shivammathur/setup-postgres@v2
      with:
        postgres-version: '15'
        postgres-db: mydatabase
        postgres-user: jericho1050
        postgres-password: ${{ secrets.PASSWORD }}
    - name: Run Django unit tests
      env:
        PASSWORD : ${{ secrets.PASSWORD }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python manage.py makemigrations
        python manage.py migrate
        python manage.py test