version: '3'

services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    web:
        build: .
        volumes:
            - .:/usr/src/app
        ports:
            - "5432:5432"
